// Mocks generated by Mockito 5.4.5 from annotations
// in jitta_rank/test/mocks/features/stock_detail/mock_stock_detail_local_datasource.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:jitta_rank/features/stock_detail/data/datasources/stock_detail_local_datasource.dart'
    as _i3;
import 'package:jitta_rank/features/stock_detail/data/models/stock_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeStockModel_0 extends _i1.SmartFake implements _i2.StockModel {
  _FakeStockModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [StockDetailLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockStockDetailLocalDatasource extends _i1.Mock
    implements _i3.StockDetailLocalDatasource {
  MockStockDetailLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.StockModel> getStockDetail(int? stockId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStockDetail,
          [stockId],
        ),
        returnValue: _i4.Future<_i2.StockModel>.value(_FakeStockModel_0(
          this,
          Invocation.method(
            #getStockDetail,
            [stockId],
          ),
        )),
      ) as _i4.Future<_i2.StockModel>);

  @override
  _i4.Future<void> saveStockDetail(_i2.StockModel? stockDetail) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveStockDetail,
          [stockDetail],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
