import 'package:hive_ce_flutter/hive_ce_flutter.dart';
import 'package:jitta_rank/features/stock_detail/data/models/stock_model.dart';
import 'package:jitta_rank/features/stock_ranking/data/models/ranked_stock_model.dart';
import 'package:jitta_rank/hive_registrar.g.dart';

/// Names of the Hive boxes this app opens.
///
/// Only two boxes exist. The other nine model types (StockPrice, StockJitta,
/// the factor types, the graph types) are stored *inside* these two, so they
/// need registered adapters but not boxes of their own.
abstract final class HiveBoxes {
  static const rankedStocks = 'ranked_stocks';
  static const stockDetail = 'stock_detail';
}

abstract class StorageService {
  Future<void> init({String? path});
  Future<void> close();
}

class StorageServiceImpl implements StorageService {
  /// Hive's type registry is global to the process and throws on a duplicate
  /// typeId, so adapter registration has to happen at most once even if init()
  /// runs again (a second container build, a test re-initialising).
  static bool _adaptersRegistered = false;

  /// [path] is for tests, which have no path_provider and must point Hive at a
  /// temp directory. Production passes nothing and gets the app documents dir.
  @override
  Future<void> init({String? path}) async {
    if (path == null) {
      await Hive.initFlutter();
    } else {
      Hive.init(path);
    }
    if (!_adaptersRegistered) {
      // Generated by hive_ce_generator from the @HiveType annotations, so the
      // list cannot drift out of sync with the models the way a hand-written
      // one does.
      Hive.registerAdapters();
      _adaptersRegistered = true;
    }
    await Future.wait([
      Hive.openBox<RankedStockModel>(HiveBoxes.rankedStocks),
      Hive.openBox<StockModel>(HiveBoxes.stockDetail),
    ]);
  }

  @override
  Future<void> close() => Hive.close();
}
