// Mocks generated by Mockito 5.4.5 from annotations
// in jitta_rank/test/mocks/features/stock_ranking/mock_stock_ranking_local_datasource.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:jitta_rank/features/stock_ranking/data/datasources/stock_ranking_local_datasource.dart'
    as _i2;
import 'package:jitta_rank/features/stock_ranking/data/models/ranked_stock_model.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [StockRankingLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockStockRankingLocalDatasource extends _i1.Mock
    implements _i2.StockRankingLocalDatasource {
  MockStockRankingLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.RankedStockModel>> getStockRankings({
    int? limit,
    String? market,
    int? page,
    List<String>? sectors,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStockRankings,
          [],
          {
            #limit: limit,
            #market: market,
            #page: page,
            #sectors: sectors,
          },
        ),
        returnValue: _i3.Future<List<_i4.RankedStockModel>>.value(
            <_i4.RankedStockModel>[]),
      ) as _i3.Future<List<_i4.RankedStockModel>>);

  @override
  _i3.Future<void> saveStockRankings(
          List<_i4.RankedStockModel>? stockRankings) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveStockRankings,
          [stockRankings],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
